import {createApp} from 'vue'
import {createPinia} from 'pinia'
import App from './App.vue'
import router from './router'
import './style.css'
import './capabilities.css'
import './enhancements.css'
import './navigation.css'
import './assignment-enhancements.css'
createApp(App).use(createPinia()).use(router).mount('#app')
