<script setup lang="ts">
import{onMounted,ref,watch}from'vue'
import{api}from'../api/client'
const courses=ref<any[]>([]),courseId=ref(0),sessionId=ref<number>(),question=ref(''),history=ref<any[]>([]),error=ref(''),loading=ref(false)
async function load(){courses.value=(await api.get('/courses')).data;if(courses.value.length)courseId.value=courses.value[0].id}
watch(courseId,()=>{sessionId.value=undefined;history.value=[]})
async function ask(){if(!question.value.trim()||!courseId.value)return;loading.value=true;error.value='';const userText=question.value;history.value.push({role:'user',content:userText});question.value='';try{if(!sessionId.value)sessionId.value=(await api.post('/qa/sessions',{course_id:courseId.value,title:`${courses.value.find(x=>x.id===courseId.value)?.name}答疑`})).data.id;const data=(await api.post(`/qa/sessions/${sessionId.value}/messages`,{content:userText})).data;history.value.push({role:'assistant',content:data.answer,citations:data.citations,confidence:data.confidence,insufficient:data.insufficient_evidence})}catch(e:any){error.value=e.message}finally{loading.value=false}}
onMounted(()=>load().catch(e=>error.value=e.message))
</script>
<template><div class="page"><div class="page-title"><div><h1>课堂智能答疑</h1><p>从已加入或负责的课程中选择课程，回答仅使用该课程知识库。</p></div><label class="course-picker">答疑课程<select v-model.number="courseId"><option v-for="c in courses" :value="c.id">{{c.name}} · {{c.subject}}</option></select></label></div><div v-if="!courses.length" class="card empty">暂无可用课程，请先加入课程</div><div v-else class="chat-layout"><div class="card chat-history"><div v-if="!history.length" class="empty">请选择课程并提出问题</div><div v-for="item in history" :class="['chat-message',item.role]"><div class="bubble">{{item.content}}</div><div v-if="item.citations?.length" class="chat-citations"><span v-for="c in item.citations">{{c.filename}} · 第 {{c.chunk_index+1}} 块</span></div><small v-if="item.role==='assistant'">置信度 {{Math.round(item.confidence*100)}}% <b v-if="item.insufficient">· 建议转交教师</b></small></div></div><div class="card chat-compose"><textarea v-model="question" placeholder="输入关于当前课程的问题……" @keydown.ctrl.enter="ask"></textarea><button :disabled="loading||!question.trim()" @click="ask">{{loading?'正在检索和回答…':'发送问题'}}</button><p class="muted">Ctrl + Enter 发送</p><p class="error">{{error}}</p></div></div></div></template>
