<script setup lang="ts">
import{computed,onMounted,ref}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),rows=ref<any[]>([]),discover=ref<any[]>([]),selected=ref<any>(),students=ref<any[]>([]),requests=ref<any[]>([]),managers=ref<any[]>([]),teachers=ref<any[]>([])
const importFile=ref<File>(),defaultPassword=ref('Student123!'),importResult=ref<any>(),managerId=ref<number>(),reason=ref(''),editingId=ref(0),error=ref(''),message=ref('')
const form=ref({name:'',subject:'',grade_level:'',description:''})
const canCreate=computed(()=>['teacher','admin'].includes(auth.user?.role||'')),isStudent=computed(()=>auth.user?.role==='student')
async function load(){rows.value=(await api.get('/courses')).data;if(isStudent.value)discover.value=(await api.get('/courses/discover')).data}
function cancelEdit(){editingId.value=0;form.value={name:'',subject:'',grade_level:'',description:''}}
async function saveCourse(){try{error.value='';if(editingId.value)await api.patch(`/courses/${editingId.value}`,form.value);else await api.post('/courses',form.value);message.value=editingId.value?'课程信息已更新':'课程创建成功';cancelEdit();await load()}catch(e:any){error.value=e.message}}
function editCourse(course:any){editingId.value=course.id;form.value={name:course.name,subject:course.subject,grade_level:course.grade_level||'',description:course.description||''};window.scrollTo({top:0,behavior:'smooth'})}
async function removeCourse(course:any){if(!confirm(`确定删除课程《${course.name}》吗？课程将归档且不再展示。`))return;try{await api.delete(`/courses/${course.id}`);message.value='课程已删除';await load()}catch(e:any){error.value=e.message}}
async function apply(course:any){try{await api.post(`/courses/${course.id}/join-requests`,{reason:reason.value||null});course.request_status='pending';message.value='申请已提交，等待课程负责人审批'}catch(e:any){error.value=e.message}}
async function manage(course:any){selected.value=course;const [s,r,m,t]=await Promise.all([api.get(`/courses/${course.id}/students`),api.get(`/courses/${course.id}/join-requests`),api.get(`/courses/${course.id}/managers`),api.get('/users?role=teacher')]);students.value=s.data;requests.value=r.data;managers.value=m.data;teachers.value=t.data;managerId.value=teachers.value[0]?.id}
async function review(id:number,action:string){await api.patch(`/course-join-requests/${id}`,{action,comment:action==='approve'?'同意加入课程':'暂不符合加入条件'});message.value='申请已处理';await manage(selected.value)}
function pickImport(e:Event){importFile.value=(e.target as HTMLInputElement).files?.[0]}
async function importStudents(){if(!importFile.value)return;const data=new FormData();data.append('default_password',defaultPassword.value);data.append('file',importFile.value);importResult.value=(await api.post(`/courses/${selected.value.id}/students/import`,data)).data;await manage(selected.value)}
async function addManager(){if(!managerId.value)return;await api.post(`/courses/${selected.value.id}/managers`,{user_id:managerId.value});await manage(selected.value)}
onMounted(()=>load().catch((e:any)=>error.value=e.message))
</script>
<template><div class="page">
  <div class="page-title"><div><h1>{{canCreate?'课程中心':'我的课程'}}</h1><p>{{canCreate?'创建并维护课程，管理负责人、审批与学生名单。':'仅展示已经审批加入的课程。'}}</p></div></div>
  <p v-if="message" class="notice success-box">{{message}}</p><p v-if="error" class="notice error">{{error}}</p>
  <form v-if="canCreate" class="card" @submit.prevent="saveCourse"><div class="section-header"><h2>{{editingId?'修改课程':'创建新课程'}}</h2><button v-if="editingId" type="button" class="secondary" @click="cancelEdit">取消修改</button></div><div class="form-grid"><label>课程名称 *<input v-model.trim="form.name" required maxlength="200"></label><label>学科 *<input v-model.trim="form.subject" required maxlength="100"></label><label>年级/学段 *<input v-model.trim="form.grade_level" required maxlength="100"></label></div><label>课程描述 *<textarea v-model.trim="form.description" required maxlength="5000"></textarea></label><button type="submit">{{editingId?'保存课程修改':'创建课程'}}</button></form>
  <section class="card"><h2>{{canCreate?'全部课程':'已加入课程'}} <span class="badge">{{rows.length}}</span></h2><div v-if="!rows.length" class="empty">暂无课程</div><div class="course-grid"><article v-for="x in rows" :key="x.id" class="course-card"><div class="course-subject">{{x.subject}}</div><h3>{{x.name}}</h3><p>{{x.description}}</p><div class="meta"><span>{{x.grade_level}}</span><span v-if="x.is_manager" class="status approved">我负责的课程</span></div><div class="inline-actions"><button v-if="canCreate&&x.is_manager" @click="manage(x)">管理成员</button><button v-if="canCreate&&x.is_manager" class="secondary" @click="editCourse(x)">修改</button><button v-if="canCreate&&x.is_manager" class="danger" @click="removeCourse(x)">删除</button><router-link class="button-link secondary" :to="`/knowledge?course=${x.id}`">知识库</router-link></div></article></div></section>
  <section v-if="isStudent" class="card"><h2>发现课程</h2><div class="course-grid"><article v-for="x in discover" :key="x.id" class="course-card"><h3>{{x.name}}</h3><p>{{x.description}}</p><textarea v-if="!x.request_status||x.request_status==='rejected'" v-model="reason" placeholder="申请理由（可选）"></textarea><button v-if="!x.request_status||x.request_status==='rejected'" @click="apply(x)">申请加入</button><span v-else class="status pending_review">等待审批</span></article></div></section>
  <div v-if="selected&&canCreate" class="modal-backdrop" @click.self="selected=null"><div class="modal wide"><button class="modal-close" @click="selected=null">×</button><h2>{{selected.name}} · 课程成员管理</h2><div class="management-grid"><section><h3>批量导入学生</h3><p class="muted">CSV 必须含 username、display_name，可选 email、password。</p><input type="file" accept=".csv" @change="pickImport"><label>统一初始密码<input type="password" v-model="defaultPassword"></label><button :disabled="!importFile" @click="importStudents">导入名单</button><p v-if="importResult">成功 {{importResult.success}}，失败 {{importResult.failed}}</p></section><section><h3>待审批申请</h3><div v-if="!requests.length" class="empty">暂无待审批申请</div><div v-for="r in requests" :key="r.id" class="request-item"><div><strong>{{r.student_name}}</strong><small>{{r.reason||'未填写理由'}}</small></div><button @click="review(r.id,'approve')">同意</button><button class="danger" @click="review(r.id,'reject')">拒绝</button></div></section><section><h3>课程负责人</h3><div v-for="m in managers" :key="m.id" class="member-row"><span>{{m.display_name}}</span><span class="status approved">负责人</span></div><div class="inline-actions"><select v-model.number="managerId"><option v-for="t in teachers" :value="t.id">{{t.display_name}}</option></select><button @click="addManager">添加</button></div></section><section><h3>已加入学生 <span class="badge">{{students.length}}</span></h3><div v-for="s in students" :key="s.id" class="member-row"><span>{{s.display_name}}（{{s.username}}）</span></div></section></div></div></div>
</div></template>
