<script setup lang="ts">
import{computed,onActivated,ref,watch}from'vue'
import{useRoute}from'vue-router'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'

const auth=useAuthStore(),route=useRoute()
const courses=ref<any[]>([]),courseId=ref(Number(route.query.course)||0),category=ref('textbook')
const files=ref<File[]>([]),documents=ref<any[]>([]),query=ref(''),result=ref<any[]>([]),batch=ref<any>()
const message=ref(''),loading=ref(false),webLoading=ref(false)
const webKeyword=ref(''),webUrl=ref(''),webResults=ref<any[]>([]),webDrafts=ref<any[]>([])
const canUpload=computed(()=>['teacher','admin'].includes(auth.user?.role||'')&&Boolean(courses.value.find(c=>c.id===courseId.value)?.is_manager))

async function loadCourses(){courses.value=(await api.get('/courses')).data;if(!courseId.value&&courses.value.length)courseId.value=courses.value[0].id}
async function loadDocuments(){if(!courseId.value){documents.value=[];return}documents.value=(await api.get(`/courses/${courseId.value}/documents`)).data}
async function loadWebDrafts(){if(!courseId.value||!canUpload.value){webDrafts.value=[];return}webDrafts.value=(await api.get(`/courses/${courseId.value}/web-imports`)).data}
function selectFiles(event:Event){files.value=Array.from((event.target as HTMLInputElement).files||[])}
async function upload(){if(!files.value.length)return;loading.value=true;message.value='';const form=new FormData();form.append('category',category.value);files.value.forEach(file=>form.append('files',file));try{batch.value=(await api.post(`/courses/${courseId.value}/documents/batch`,form)).data;message.value=`上传完成：成功 ${batch.value.uploaded}，重复 ${batch.value.duplicates}，失败 ${batch.value.failed}`;files.value=[];await loadDocuments()}catch(e:any){message.value=e.message}finally{loading.value=false}}
async function search(){if(!query.value.trim())return;loading.value=true;try{result.value=(await api.post('/knowledge/search',{course_id:courseId.value,query:query.value,top_k:8})).data}catch(e:any){message.value=e.message}finally{loading.value=false}}
async function searchWeb(){if(!webKeyword.value.trim())return;webLoading.value=true;message.value='';try{webResults.value=(await api.post(`/courses/${courseId.value}/web-imports/search`,{keyword:webKeyword.value,limit:10})).data;if(!webResults.value.length)message.value='未找到可用网页结果，可以直接粘贴网页地址。'}catch(e:any){message.value=e.message}finally{webLoading.value=false}}
async function previewWeb(url?:string){const value=(url||webUrl.value).trim();if(!value)return;webLoading.value=true;message.value='';try{await api.post(`/courses/${courseId.value}/web-imports/preview`,{url:value});webUrl.value='';message.value='网页正文已抓取，请检查下方预览并确认是否入库。';await loadWebDrafts()}catch(e:any){message.value=e.message}finally{webLoading.value=false}}
async function confirmWeb(id:number){webLoading.value=true;message.value='';try{const{data}=await api.post(`/web-imports/${id}/confirm`,{category:'web_reference'});message.value=`已确认入库：${data.document.filename}，生成 ${data.document.chunks} 个知识块`;await Promise.all([loadWebDrafts(),loadDocuments()])}catch(e:any){message.value=e.message}finally{webLoading.value=false}}
async function rejectWeb(id:number){webLoading.value=true;try{await api.delete(`/web-imports/${id}`);message.value='已拒绝该网页草稿，不会写入知识库。';await loadWebDrafts()}catch(e:any){message.value=e.message}finally{webLoading.value=false}}
watch(courseId,()=>{Promise.all([loadDocuments(),loadWebDrafts()]).catch(e=>message.value=e.message);result.value=[];webResults.value=[]})
onActivated(async()=>{try{await loadCourses();await Promise.all([loadDocuments(),loadWebDrafts()])}catch(e:any){message.value=e.message}})
</script>

<template><div class="page">
  <div class="page-title"><div><h1>课程知识库</h1><p>{{canUpload?'上传本地文件，或抓取网页并确认后建立课程索引。':'查看教师确认的课程资料并进行知识检索。'}}</p></div><label class="course-picker">当前课程<select v-model.number="courseId"><option v-for="c in courses" :key="c.id" :value="c.id">{{c.name}}</option></select></label></div>
  <p v-if="message" class="notice">{{message}}</p>

  <div v-if="canUpload" class="card"><h2>批量上传学习文件</h2><div class="upload-zone"><input id="multi-files" type="file" multiple accept=".txt,.md,.pdf,.docx" @change="selectFiles"><label for="multi-files"><strong>点击选择多个文件</strong><span>支持 TXT、Markdown、PDF、DOCX；单次最多 20 个</span></label></div><div v-if="files.length" class="selected-files"><span v-for="f in files" :key="f.name">{{f.name}} · {{(f.size/1024).toFixed(1)}}KB</span></div><div class="inline-actions"><select v-model="category"><option value="textbook">教材</option><option value="courseware">课件</option><option value="question_bank">题库</option></select><button :disabled="loading||!files.length" @click="upload">{{loading?'处理中…':`上传 ${files.length||''} 个文件`}}</button></div><div v-if="batch" class="batch-results"><div v-for="x in batch.results" :key="x.filename" :class="['upload-result',x.status]"><strong>{{x.filename}}</strong><span>{{x.status==='ready'?'上传成功':x.status==='duplicate'?x.message:x.error}}</span></div></div></div>

  <div v-if="canUpload" class="card web-import"><div class="section-header"><div><h2>从网络获取学习资料</h2><p class="muted">参考 course_spider 的正文提取方式。抓取结果只生成临时预览，必须由课程负责人确认后才会进入知识库并参与 AI 输出。</p></div><span class="badge">24 小时内确认</span></div><div class="notice web-warning">请确认网页允许使用，尊重版权与站点规则。系统会拦截内网地址、异常重定向、超大内容和 robots.txt 禁止的页面。</div><div class="search-bar"><input v-model="webKeyword" placeholder="搜索学习主题，例如：Python 装饰器教程" @keyup.enter="searchWeb"><button :disabled="webLoading" @click="searchWeb">搜索网页</button></div><div v-if="webResults.length" class="web-search-results"><div v-for="item in webResults" :key="item.url" class="web-result"><div><strong>{{item.title}}</strong><a :href="item.url" target="_blank" rel="noopener noreferrer">查看原网页</a></div><small>{{item.url}}</small><button class="secondary" :disabled="webLoading" @click="previewWeb(item.url)">抓取并预览</button></div></div><div class="search-bar direct-url"><input v-model="webUrl" type="url" placeholder="也可以直接粘贴 http/https 网页地址" @keyup.enter="previewWeb()"><button :disabled="webLoading||!webUrl.trim()" @click="previewWeb()">抓取地址</button></div>
    <div v-if="webDrafts.length" class="web-drafts"><h3>待确认与历史抓取</h3><article v-for="draft in webDrafts" :key="draft.id" class="web-draft"><div class="section-header"><div><strong>{{draft.title}}</strong><p><a :href="draft.resolved_url" target="_blank" rel="noopener noreferrer">{{draft.source_domain}}</a> · {{draft.metadata?.character_count||draft.content.length}} 字符</p></div><span :class="['status',draft.status]">{{draft.status}}</span></div><pre v-if="draft.status==='pending'">{{draft.content.slice(0,5000)}}</pre><div v-if="draft.status==='pending'" class="inline-actions"><button :disabled="webLoading" @click="confirmWeb(draft.id)">确认并写入知识库</button><button class="danger" :disabled="webLoading" @click="rejectWeb(draft.id)">拒绝</button><span class="muted">到期：{{new Date(draft.expires_at).toLocaleString()}}</span></div></article></div>
  </div>

  <div class="card"><h2>知识库文件 <span class="badge">{{documents.length}}</span></h2><div v-if="!documents.length" class="empty">当前课程尚未上传资料</div><div class="document-table" v-else><div class="document-row heading"><span>文件名</span><span>类型</span><span>分块</span><span>状态</span><span>上传时间</span></div><div class="document-row" v-for="doc in documents" :key="doc.id"><span class="document-name">📄 {{doc.filename}} <a v-if="doc.source_url" :href="doc.source_url" target="_blank" rel="noopener noreferrer" title="打开来源">↗</a></span><span>{{doc.category}}</span><span>{{doc.chunks}}</span><span :class="['status',doc.status]">{{doc.status}}</span><span>{{new Date(doc.created_at).toLocaleString()}}</span></div></div></div>
  <div class="card"><h2>知识检索</h2><div class="search-bar"><input v-model="query" placeholder="例如：过拟合有哪些解决方法？" @keyup.enter="search"><button :disabled="loading" @click="search">检索</button></div><div v-for="x in result" :key="x.chunk_id" class="search-result"><div><strong>{{x.filename}}</strong><span>第 {{x.chunk_index+1}} 块 · 相关度 {{x.rerank_score?.toFixed(2)}}</span></div><p>{{x.content}}</p></div></div>
</div></template>
