<script setup lang="ts">
import{computed,onActivated,ref,watch}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),courses=ref<any[]>([]),students=ref<any[]>([]),reports=ref<any[]>([]),result=ref<any>(),error=ref(''),message=ref(''),loading=ref(false)
const isParent=computed(()=>auth.user?.role==='parent')
const form=ref({student_id:1,course_id:0,period_type:'week',period_start:new Date(Date.now()-604800000).toISOString(),period_end:new Date().toISOString()})
async function load(){if(isParent.value){students.value=(await api.get('/parent/students')).data;if(students.value.length)form.value.student_id=students.value[0].id;await loadParentReports()}else{courses.value=(await api.get('/courses/managed')).data;if(courses.value.length&&!form.value.course_id)form.value.course_id=courses.value[0].id}}
async function loadParentReports(){if(!form.value.student_id)return;reports.value=(await api.get(`/parent/reports?student_id=${form.value.student_id}`)).data}
async function loadStudents(){if(!form.value.course_id||isParent.value)return;students.value=(await api.get(`/courses/${form.value.course_id}/students`)).data;if(students.value.length)form.value.student_id=students.value[0].id}
async function run(){loading.value=true;error.value='';try{result.value=(await api.post('/reports/generate',form.value)).data;message.value='报告草稿生成成功，请核对后发布'}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function publish(){try{await api.patch(`/reports/${result.value.id}/review`,{action:'publish',comment:'教师审核通过'});result.value.status='published';message.value='报告已发布，授权家长现在可以查看'}catch(e:any){error.value=e.message}}
watch(()=>form.value.course_id,()=>loadStudents().catch((e:any)=>error.value=e.message));watch(()=>form.value.student_id,()=>{if(isParent.value)loadParentReports().catch((e:any)=>error.value=e.message)})
onActivated(async()=>{try{await load();await loadStudents()}catch(e:any){error.value=e.message}})
</script>
<template><div class="page"><div class="page-title"><div><h1>{{isParent?'孩子的学习报告':'学习报告管理'}}</h1><p>{{isParent?'按孩子分别查看教师已审核发布的报告，内容采用家长容易理解的表达。':'依据真实学习数据生成家长友好报告，审核后再发布。'}}</p></div><label v-if="isParent" class="course-picker">当前孩子<select v-model.number="form.student_id"><option v-for="s in students" :value="s.id">{{s.display_name}}（{{s.username}}）</option></select></label></div><p class="notice error" v-if="error">{{error}}</p><p class="notice success-box" v-if="message">{{message}}</p><template v-if="isParent"><div v-if="!students.length" class="card empty">当前家长账号尚未绑定学生</div><div v-else-if="!reports.length" class="card empty">该学生暂无已发布的学习报告</div><article v-for="r in reports" :key="r.id" class="card report-card"><div class="section-header"><h2>{{r.period_type==='week'?'学习周报':'学习月报'}}</h2><span class="status published">已发布</span></div><div class="grid report-metrics"><div><strong>整体掌握情况</strong><div class="metric">{{Math.round((r.metrics.average_mastery||0)*100)}}%</div><small>这是已记录知识点的平均水平</small></div><div><strong>本期有数据的知识点</strong><div class="metric">{{r.metrics.knowledge_points}}</div><small>数据较少时仅作阶段参考</small></div></div><h3>本阶段概况</h3><p>{{r.content.overview||r.content.summary}}</p><h3>值得肯定</h3><ul><li v-for="x in (r.content.highlights||[r.content.progress]).filter(Boolean)">{{x}}</li></ul><h3>接下来重点关注</h3><ul><li v-for="x in (r.content.needs_attention||r.content.weaknesses||[])">{{x}}</li></ul><h3>在家可以这样配合</h3><ol><li v-for="x in (r.content.action_plan||r.content.suggestions||[])">{{x}}</li></ol><p class="encouragement">{{r.content.encouragement}}</p><p class="muted">{{r.content.metrics_explanation}}</p></article></template><template v-else><div class="card"><h2>生成报告</h2><div class="form-grid"><label>课程<select v-model.number="form.course_id"><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label><label>学生<select v-model.number="form.student_id"><option v-for="s in students" :value="s.id">{{s.display_name}}（{{s.username}}）</option></select></label><label>报告周期<select v-model="form.period_type"><option value="week">周报</option><option value="month">月报</option></select></label></div><div v-if="!students.length" class="empty">该课程暂无学生提交记录</div><button v-else :disabled="loading" @click="run">{{loading?'生成中…':'生成待审核报告'}}</button></div><div v-if="result" class="card report-card"><div class="section-header"><h2>家长端报告预览</h2><span :class="['status',result.status]">{{result.status}}</span></div><h3>本阶段概况</h3><p>{{result.content.overview}}</p><h3>值得肯定</h3><ul><li v-for="x in result.content.highlights">{{x}}</li></ul><h3>需要关注</h3><ul><li v-for="x in result.content.needs_attention">{{x}}</li></ul><h3>家庭行动建议</h3><ol><li v-for="x in result.content.action_plan">{{x}}</li></ol><p class="encouragement">{{result.content.encouragement}}</p><p class="muted">{{result.content.metrics_explanation}}</p><button v-if="result.status!=='published'" @click="publish">审核并发布</button></div></template></div></template>
