<script setup lang="ts">
import{computed,onMounted,ref,watch}from'vue'
import{api}from'../api/client'
import{useAuthStore}from'../stores/auth'
const auth=useAuthStore(),courses=ref<any[]>([]),students=ref<any[]>([]),reports=ref<any[]>([]),result=ref<any>(),error=ref(''),message=ref(''),loading=ref(false)
const isParent=computed(()=>auth.user?.role==='parent')
const form=ref({student_id:1,course_id:0,period_type:'week',period_start:new Date(Date.now()-604800000).toISOString(),period_end:new Date().toISOString()})
async function load(){if(isParent.value){reports.value=(await api.get('/parent/reports')).data}else{courses.value=(await api.get('/courses')).data;if(courses.value.length&&!form.value.course_id)form.value.course_id=courses.value[0].id}}
async function loadStudents(){if(!form.value.course_id||isParent.value)return;students.value=(await api.get(`/courses/${form.value.course_id}/students`)).data;if(students.value.length)form.value.student_id=students.value[0].id}
async function run(){loading.value=true;try{result.value=(await api.post('/reports/generate',form.value)).data;message.value='报告草稿生成成功，请核对后发布'}catch(e:any){error.value=e.message}finally{loading.value=false}}
async function publish(){try{await api.patch(`/reports/${result.value.id}/review`,{action:'publish',comment:'教师审核通过'});result.value.status='published';message.value='报告已发布，授权家长现在可以查看'}catch(e:any){error.value=e.message}}
watch(()=>form.value.course_id,()=>loadStudents().catch(e=>error.value=e.message))
onMounted(async()=>{try{await load();await loadStudents()}catch(e:any){error.value=e.message}})
</script>
<template><div class="page"><div class="page-title"><div><h1>{{isParent?'孩子的学习报告':'学习报告管理'}}</h1><p>{{isParent?'这里只展示教师已审核发布的报告。':'依据真实学习数据生成报告，审核后再向家长发布。'}}</p></div></div><p class="notice error" v-if="error">{{error}}</p><p class="notice success-box" v-if="message">{{message}}</p><template v-if="isParent"><div v-if="!reports.length" class="card empty">暂无已发布的学习报告</div><article v-for="r in reports" :key="r.id" class="card report-card"><div class="section-header"><h2>{{r.period_type==='week'?'学习周报':'学习月报'}}</h2><span class="status published">已发布</span></div><div class="grid"><div><strong>平均掌握度</strong><div class="metric">{{Math.round((r.metrics.average_mastery||0)*100)}}%</div></div><div><strong>覆盖知识点</strong><div class="metric">{{r.metrics.knowledge_points}}</div></div></div><h3>报告总结</h3><p>{{r.content.summary}}</p><h3>进步与建议</h3><p>{{r.content.progress}}</p><ul><li v-for="x in r.content.suggestions">{{x}}</li></ul></article></template><template v-else><div class="card"><h2>生成报告</h2><div class="form-grid"><label>课程<select v-model.number="form.course_id"><option v-for="c in courses" :value="c.id">{{c.name}}</option></select></label><label>学生<select v-model.number="form.student_id"><option v-for="s in students" :value="s.id">{{s.display_name}}（{{s.username}}）</option></select></label><label>报告周期<select v-model="form.period_type"><option value="week">周报</option><option value="month">月报</option></select></label></div><div v-if="!students.length" class="empty">该课程暂无学生提交记录</div><button v-else :disabled="loading" @click="run">{{loading?'生成中…':'生成待审核报告'}}</button></div><div v-if="result" class="card"><div class="section-header"><h2>报告预览</h2><span :class="['status',result.status]">{{result.status}}</span></div><div class="grid"><div><strong>平均掌握度</strong><div class="metric">{{Math.round((result.metrics.average_mastery||0)*100)}}%</div></div><div><strong>知识点数量</strong><div class="metric">{{result.metrics.knowledge_points}}</div></div></div><pre class="answer">{{JSON.stringify(result.content,null,2)}}</pre><button v-if="result.status!=='published'" @click="publish">审核并发布</button></div></template></div></template>
